Dcm4chee for tests (#1)
* Update parameters of ``storeInstances`` API method

* Fix request helper functions for POST method

* Create dcm4chee-docker-compose.yml

* Create dcm4chee-docker-compose.env

* Update dcm4chee-docker-compose.yml

* Try to run dcm4chee with docker-compose for travis

* Fix name of environment file for docker compose

* try changing postgres port

Address this error from travis: 
```
Digest: sha256:4208948ecf63c111ea40a367bb3af7a61b8be235587e597b762480eaeeeca014
Status: Downloaded newer image for dcm4che/dcm4chee-arc-psql:5.13.3
Creating dicomwebclient_db_1 ... 
Creating dicomwebclient_ldap_1 ... 
Creating dicomwebclient_ldap_1
Creating dicomwebclient_db_1
ERROR: for dicomwebclient_db_1  Cannot start service db: driver failed programming external connectivity on endpoint dicomwebclient_db_1 (e37d2be345d7e4edd272cc5f2c05c3d351f5386848b3749d00f96b8fe8c1a121): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint dicomwebclient_db_1 (e37d2be345d7e4edd272cc5f2c05c3d351f5386848b3749d00f96b8fe8c1a121): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

* Switch dcm4chee postgres port back to default

* Put dcm4chee docker into daemon mode for testing

* Add loop to wait for server to come up (travis)

* Shutdown system postgres in travis

Workaround suggested here:

https://github.com/travis-ci/travis-ci/issues/4842#issuecomment-311527059

* Avoid travis build failure

Only include commands that are meant to succeed

* Add test framework

TODO: port the client to be node compatible with fetch
instead of XMLHttpRequest.

* Run the npm test in travis

* Install before testing

* Add tape dependency for testing

* Fix dependencies and lock for tests

* Add tape for running tests